version: '2'

services:
  my:
     image: php:7.0-apache
     volumes:
       - ./my:/var/www/html
     ports:
       - "4000:80"

  bad:
     image: nginx
     volumes:
       - ./bad:/usr/share/nginx/html
     ports:
       - "4001:80"
